In [291]:
import pandas as pd
import datetime
from datetime import date
import numpy as np

In [292]:
# Create dummy dataset for use with GUI

In [293]:
x = pd.read_csv('x_test.csv')
y = pd.read_csv('y_test.csv')

In [294]:
x.head()

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Western Addition,Westwood Highlands,Westwood Park,Yerba Buena Island,Friday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [295]:
df = pd.read_csv('SF_neighborhoods.csv')
neighbourhoods = []
num_neighbourhoods = len(df.index)
for i in range(0,num_neighbourhoods):
    neighbourhoods.append(df.iloc[i,2])

In [296]:
days = ['Friday','Saturday','Sunday','Thursday','Tuesday','Wednesday']

In [297]:
for neighbourhood in neighbourhoods:
    try:
        x = x.drop(columns=neighbourhood)
    except:
        pass
x = x.drop(columns=days)

In [298]:
x

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Openings 4 days ago,Openings 5 days ago,Openings 6 days ago,Openings 7 days ago,Openings 14 days ago,Openings 30 days ago,Openings 365 days ago,Last 7 days openings,Last 14 days openings,Last 28 days openings
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.016502
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.0,0.004878,0.0,0.000000,0.0,0.004878,0.000000,0.004329,0.011494,0.029703
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14620,0.000000,0.027397,0.027397,0.013699,0.000000,0.000000,0.013699,0.027397,0.054795,0.051282,...,0.0,0.000000,0.0,0.004878,0.0,0.000000,0.000000,0.004329,0.003831,0.013201
14621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027397,0.000000,0.000000,...,0.0,0.000000,0.0,0.014634,0.0,0.000000,0.000000,0.012987,0.011494,0.036304
14622,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.027397,0.013699,0.013699,0.012821,...,0.0,0.000000,0.0,0.000000,0.0,0.004878,0.000000,0.000000,0.015326,0.013201
14623,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,0.013699,0.041096,0.013699,0.051282,...,0.0,0.000000,0.0,0.004878,0.0,0.000000,0.000000,0.008658,0.007663,0.009901
14624,0.000000,0.000000,0.013699,0.000000,0.000000,0.041096,0.013699,0.000000,0.013699,0.025641,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.004878,0.004329,0.007663,0.009901

In [299]:
y

       Todays Reports
0                 6.0
1                 8.0
2                 3.0
3                 2.0
4                 0.0
...               ...
14620             1.0
14621             0.0
14622             0.0
14623             5.0
14624             0.0

[14625 rows x 1 columns]

In [300]:
merged = pd.concat([x,y], axis = 1, join = "inner")
merged

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Openings 5 days ago,Openings 6 days ago,Openings 7 days ago,Openings 14 days ago,Openings 30 days ago,Openings 365 days ago,Last 7 days openings,Last 14 days openings,Last 28 days openings,Todays Reports
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.016502,6.0
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601,8.0
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601,3.0
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.004878,0.0,0.000000,0.0,0.004878,0.000000,0.004329,0.011494,0.029703,2.0
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14620,0.000000,0.027397,0.027397,0.013699,0.000000,0.000000,0.013699,0.027397,0.054795,0.051282,...,0.000000,0.0,0.004878,0.0,0.000000,0.000000,0.004329,0.003831,0.013201,1.0
14621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027397,0.000000,0.000000,...,0.000000,0.0,0.014634,0.0,0.000000,0.000000,0.012987,0.011494,0.036304,0.0
14622,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.027397,0.013699,0.013699,0.012821,...,0.000000,0.0,0.000000,0.0,0.004878,0.000000,0.000000,0.015326,0.013201,0.0
14623,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,0.013699,0.041096,0.013699,0.051282,...,0.000000,0.0,0.004878,0.0,0.000000,0.000000,0.008658,0.007663,0.009901,5.0
14624,0.000000,0.000000,0.013699,0.000000,0.000000,0.041096,0.013699,0.000000,0.013699,0.025641,...,0.000000,0.0,0.000000,0.0,0.000000,0.004878,0.004329,0.007663,0.009901,0.0

In [301]:
num_neighbourhoods = len(neighbourhoods)
num_records = len(merged.index)
num_dates = num_records/num_neighbourhoods
#check num_dates has zero decimal places
num_dates

125.0

In [302]:
current_date = date.today()
current_date_array = []
i = 0
while i < num_neighbourhoods:
    current_date_array.append(current_date)
    i+=1

In [303]:
dates = pd.DataFrame()
final_dates = pd.DataFrame()
dates['Date'] = current_date_array
final_dates['Date'] = current_date_array
i = 1
while i < num_dates:
    final_dates = final_dates.append(dates)
    current_date += datetime.timedelta(days=1)
    dates['Date'] = current_date
    i+=1
final_dates.reset_index(drop=True, inplace=True)
final_dates

             Date
0      2021-01-23
1      2021-01-23
2      2021-01-23
3      2021-01-23
4      2021-01-23
...           ...
14620  2021-05-26
14621  2021-05-26
14622  2021-05-26
14623  2021-05-26
14624  2021-05-26

[14625 rows x 1 columns]

In [304]:
merged = pd.concat([merged,final_dates], axis = 1, join = "inner")
merged

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Openings 6 days ago,Openings 7 days ago,Openings 14 days ago,Openings 30 days ago,Openings 365 days ago,Last 7 days openings,Last 14 days openings,Last 28 days openings,Todays Reports,Date
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.016502,6.0,2021-01-23
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601,8.0,2021-01-23
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601,3.0,2021-01-23
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.0,0.000000,0.0,0.004878,0.000000,0.004329,0.011494,0.029703,2.0,2021-01-23
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,2021-01-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14620,0.000000,0.027397,0.027397,0.013699,0.000000,0.000000,0.013699,0.027397,0.054795,0.051282,...,0.0,0.004878,0.0,0.000000,0.000000,0.004329,0.003831,0.013201,1.0,2021-05-26
14621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027397,0.000000,0.000000,...,0.0,0.014634,0.0,0.000000,0.000000,0.012987,0.011494,0.036304,0.0,2021-05-26
14622,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.027397,0.013699,0.013699,0.012821,...,0.0,0.000000,0.0,0.004878,0.000000,0.000000,0.015326,0.013201,0.0,2021-05-26
14623,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,0.013699,0.041096,0.013699,0.051282,...,0.0,0.004878,0.0,0.000000,0.000000,0.008658,0.007663,0.009901,5.0,2021-05-26
14624,0.000000,0.000000,0.013699,0.000000,0.000000,0.041096,0.013699,0.000000,0.013699,0.025641,...,0.0,0.000000,0.0,0.000000,0.004878,0.004329,0.007663,0.009901,0.0,2021-05-26

In [305]:
neighbourhood_data = pd.DataFrame()
neighbourhood_data['Neighborhood'] = neighbourhoods
final_neighbourhoods = pd.DataFrame()
final_neighbourhoods['Neighborhood'] = neighbourhoods
i = 1
while i < num_dates:
    final_neighbourhoods = final_neighbourhoods.append(neighbourhood_data)
    i+=1
final_neighbourhoods.reset_index(drop=True, inplace=True)
final_neighbourhoods

                 Neighborhood
0                    Seacliff
1                 Lake Street
2      Presidio National Park
3            Presidio Terrace
4              Inner Richmond
...                       ...
14620          Corona Heights
14621         Ashbury Heights
14622           Eureka Valley
14623        St. Francis Wood
14624         Sherwood Forest

[14625 rows x 1 columns]

In [306]:
merged = pd.concat([merged,final_neighbourhoods], axis = 1, join = "inner")
merged

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Openings 7 days ago,Openings 14 days ago,Openings 30 days ago,Openings 365 days ago,Last 7 days openings,Last 14 days openings,Last 28 days openings,Todays Reports,Date,Neighborhood
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.016502,6.0,2021-01-23,Seacliff
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601,8.0,2021-01-23,Lake Street
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601,3.0,2021-01-23,Presidio National Park
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.000000,0.0,0.004878,0.000000,0.004329,0.011494,0.029703,2.0,2021-01-23,Presidio Terrace
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,2021-01-23,Inner Richmond
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14620,0.000000,0.027397,0.027397,0.013699,0.000000,0.000000,0.013699,0.027397,0.054795,0.051282,...,0.004878,0.0,0.000000,0.000000,0.004329,0.003831,0.013201,1.0,2021-05-26,Corona Heights
14621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027397,0.000000,0.000000,...,0.014634,0.0,0.000000,0.000000,0.012987,0.011494,0.036304,0.0,2021-05-26,Ashbury Heights
14622,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.027397,0.013699,0.013699,0.012821,...,0.000000,0.0,0.004878,0.000000,0.000000,0.015326,0.013201,0.0,2021-05-26,Eureka Valley
14623,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,0.013699,0.041096,0.013699,0.051282,...,0.004878,0.0,0.000000,0.000000,0.008658,0.007663,0.009901,5.0,2021-05-26,St. Francis Wood
14624,0.000000,0.000000,0.013699,0.000000,0.000000,0.041096,0.013699,0.000000,0.013699,0.025641,...,0.000000,0.0,0.000000,0.004878,0.004329,0.007663,0.009901,0.0,2021-05-26,Sherwood Forest

In [307]:
merged.to_csv('incident_data.csv', index = False)