In [9]:
import sklearn
import pandas as pd

In [10]:
x_train = pd.read_csv('x_train.csv')

In [11]:
x_train.head()

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Western Addition,Westwood Highlands,Westwood Park,Yerba Buena Island,Friday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.013699,0.000000,0.027397,0.041096,0.013699,0.041096,0.000000,0.000000,0.027397,0.025641,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.123288,0.082192,0.041096,0.013699,0.109589,0.178082,0.191781,0.041096,0.041096,0.076923,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.027397,0.041096,0.027397,0.054795,0.013699,0.013699,0.041096,0.000000,0.013699,0.012821,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.013699,0.041096,0.027397,0.013699,0.027397,0.013699,0.013699,0.000000,0.027397,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<h3>Remove features with zero variance<h3>

In [12]:
from sklearn.feature_selection import VarianceThreshold
threshold = 0.0;
variance_threshold = VarianceThreshold(threshold = threshold) #.0005
variance_threshold.fit(x_train)

VarianceThreshold()

In [13]:
variance_threshold.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

Get columns with zero variance

In [14]:
zero_var_columns = [col for col in x_train
                   if col not in x_train.columns[variance_threshold.get_support()]]
print(len(zero_var_columns),"features have",threshold,"variance.")

0 features have 0.0 variance.

Drop all columns with threshold variance

In [15]:
x_train.drop(zero_var_columns, axis = 1)

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Western Addition,Westwood Highlands,Westwood Park,Yerba Buena Island,Friday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.013699,0.000000,0.027397,0.041096,0.013699,0.041096,0.000000,0.000000,0.027397,0.025641,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.123288,0.082192,0.041096,0.013699,0.109589,0.178082,0.191781,0.041096,0.041096,0.076923,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.027397,0.041096,0.027397,0.054795,0.013699,0.013699,0.041096,0.000000,0.013699,0.012821,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.013699,0.041096,0.027397,0.013699,0.027397,0.013699,0.013699,0.000000,0.027397,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43870,0.000000,0.013699,0.041096,0.054795,0.013699,0.013699,0.013699,0.013699,0.013699,0.012821,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43871,0.000000,0.027397,0.000000,0.013699,0.000000,0.013699,0.027397,0.068493,0.000000,0.012821,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43872,0.068493,0.164384,0.054795,0.109589,0.164384,0.082192,0.095890,0.041096,1.000000,0.230769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43873,0.027397,0.027397,0.000000,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
43874,0.013699,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
x_train.to_csv('x_train_zero_variance_removed.csv', index = False)