In [98]:
import pandas as pd

In [99]:
# Create dummy dataset for use with GUI

In [100]:
x = pd.read_csv('x_test.csv')
y = pd.read_csv('y_test.csv')

In [101]:
x.head()

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Western Addition,Westwood Highlands,Westwood Park,Yerba Buena Island,Friday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [102]:
df = pd.read_csv('SF_neighborhoods.csv')
neighborhoods = []
num_neighborhoods = len(df.index)
for i in range(0,num_neighborhoods):
    neighborhoods.append(df.iloc[i,2])

In [103]:
days = ['Friday','Saturday','Sunday','Thursday','Tuesday','Wednesday']

In [104]:
for neighborhood in neighborhoods:
    try:
        x = x.drop(columns=neighborhood)
    except:
        pass
x = x.drop(columns=days)

In [108]:
x

,Reports 1 day ago,Reports 2 days ago,Reports 3 days ago,Reports 4 days ago,Reports 5 days ago,Reports 6 days ago,Reports 7 days ago,Reports 14 days ago,Reports 30 days ago,Reports 365 days ago,...,Openings 4 days ago,Openings 5 days ago,Openings 6 days ago,Openings 7 days ago,Openings 14 days ago,Openings 30 days ago,Openings 365 days ago,Last 7 days openings,Last 14 days openings,Last 28 days openings
0,0.095890,0.000000,0.041096,0.013699,0.027397,0.041096,0.068493,0.068493,0.041096,0.012821,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.016502
1,0.219178,0.164384,0.232877,0.164384,0.164384,0.178082,0.150685,0.068493,0.068493,0.115385,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601
2,0.000000,0.013699,0.027397,0.054795,0.000000,0.000000,0.013699,0.000000,0.041096,0.038462,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.003831,0.006601
3,0.013699,0.013699,0.027397,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.000000,...,0.0,0.004878,0.0,0.000000,0.0,0.004878,0.000000,0.004329,0.011494,0.029703
4,0.000000,0.000000,0.000000,0.013699,0.000000,0.000000,0.013699,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14620,0.000000,0.027397,0.027397,0.013699,0.000000,0.000000,0.013699,0.027397,0.054795,0.051282,...,0.0,0.000000,0.0,0.004878,0.0,0.000000,0.000000,0.004329,0.003831,0.013201
14621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027397,0.000000,0.000000,...,0.0,0.000000,0.0,0.014634,0.0,0.000000,0.000000,0.012987,0.011494,0.036304
14622,0.013699,0.027397,0.000000,0.013699,0.000000,0.027397,0.027397,0.013699,0.013699,0.012821,...,0.0,0.000000,0.0,0.000000,0.0,0.004878,0.000000,0.000000,0.015326,0.013201
14623,0.000000,0.013699,0.000000,0.013699,0.000000,0.000000,0.013699,0.041096,0.013699,0.051282,...,0.0,0.000000,0.0,0.004878,0.0,0.000000,0.000000,0.008658,0.007663,0.009901
14624,0.000000,0.000000,0.013699,0.000000,0.000000,0.041096,0.013699,0.000000,0.013699,0.025641,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.004878,0.004329,0.007663,0.009901

In [119]:
y

       Todays Reports
0                 6.0
1                 8.0
2                 3.0
3                 2.0
4                 0.0
...               ...
14620             1.0
14621             0.0
14622             0.0
14623             5.0
14624             0.0

[14625 rows x 1 columns]